fixed variable name and added to rke2 test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -112,7 +112,7 @@ pre vars:
       fi
       echo -e "\e[0Ksection_end:`date +%s`:${test_script##*/}\r\e[0K"
     done
-    [ -z "${EXIT_CODE}" ] && echo -e "\e[31mWARNING: One or more BB tests failed but were allowed to continue. See output of scripts above for details.\e[0m"
+    [ -z "$EXIT_FLAG" ] && echo -e "\e[31mWARNING: One or more BB tests failed but were allowed to continue. See output of scripts above for details.\e[0m"
 
 clean install:
   stage: smoke tests
@@ -134,7 +134,7 @@ clean install:
     - echo $images | jq -r '.images[].repoTags[0] | select(. != null)' | tee images.txt
     - echo -e "\e[0Ksection_end:`date +%s`:images_used\r\e[0K"
     - *test_bigbang
-    - [ -n "${EXIT_CODE}" ] && exit 123
+    - [ -n "$EXIT_FLAG" ] && exit 123
   artifacts:
     paths:
       - images.txt
@@ -176,7 +176,7 @@ upgrade:
     - echo -e "\e[0Ksection_end:`date +%s`:git_upgrade\r\e[0K"
     - *deploy_bigbang
     - *test_bigbang
-    - [ -n "${EXIT_CODE}" ] && exit 123
+    - [ -n "$EXIT_FLAG" ] && exit 123
   artifacts:
     paths:
       - "test-artifacts/"
@@ -324,6 +324,8 @@ aws/rke2/bigbang test:
     - ./scripts/hosts.sh
     - echo -e "\e[0Ksection_end:`date +%s`:host_setup\r\e[0K"
     - *test_bigbang
+    - [ -n "$EXIT_FLAG" ] && exit 123
+    
   environment:
     name: review/aws-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
   allow_failure:
