improved logging and error handling

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -96,17 +96,26 @@ pre vars:
 .test_bigbang: &test_bigbang
   - |
     set -e
+    EXIT_FLAG=0
     for test_script in $(find ./tests/tests -type f -name '*.sh' | sort); do
       echo -e "\e[0Ksection_start:`date +%s`:${test_script##*/}[collapsed=true]\r\e[0K\e[33;1m${test_script##*/}\e[37m"        
       chmod +x ${test_script}
       echo "Executing ${test_script}..."
       ./${test_script} && export EXIT_CODE=$? || export EXIT_CODE=$?
       if [[ ${EXIT_CODE} -ne 0 ]]; then
-        echo "${test_script} failed, see log output above and cluster debug."
-        # exit ${EXIT_CODE}
+        if [[ ${EXIT_CODE} -ne 123 ]]; then
+          echo -e "\e[31m${test_script} failed, see log output above and cluster debug.\e[0m"
+          exit ${EXIT_CODE}
+        fi
+        # 123 error codes are allowed to continue
+        echo -e "\e[31m${test_script} failed but was allowed to continue, see log output above and cluster debug.\e[0m"
+        EXIT_FLAG=1
       fi
       echo -e "\e[0Ksection_end:`date +%s`:${test_script##*/}\r\e[0K"
     done
+    if [[ ${EXIT_FLAG} -ne 0 ]]; then
+      echo -e "\[31mWARNING: One or more BB tests failed but were allowed to continue. See output of scripts above for details.\e[0m"
+    fi
 
 clean install:
   stage: smoke tests
@@ -128,11 +137,6 @@ clean install:
     - echo $images | jq -r '.images[].repoTags[0] | select(. != null)' | tee images.txt
     - echo -e "\e[0Ksection_end:`date +%s`:images_used\r\e[0K"
     - *test_bigbang
-    - |
-      if [[ ${EXIT_CODE} -ne 0 ]]; then
-        exit ${EXIT_CODE}
-      fi
-    
   artifacts:
     paths:
       - images.txt
@@ -167,7 +171,7 @@ upgrade:
     - echo -e "\e[0Ksection_end:`date +%s`:git_master\r\e[0K"
     - *deploy_bigbang
     - *test_bigbang
-    - PRE_EXIT_CODE=${EXIT_CODE}
+    - PRE_EXIT_CODE=${EXIT_FLAG}
     - echo "Upgrade Big Bang from ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
     - echo -e "\e[0Ksection_start:`date +%s`:git_upgrade[collapsed=true]\r\e[0K\e[33;1mGit Upgrade\e[37m"    
     - git reset --hard && git clean -fd
@@ -175,13 +179,6 @@ upgrade:
     - echo -e "\e[0Ksection_end:`date +%s`:git_upgrade\r\e[0K"
     - *deploy_bigbang
     - *test_bigbang
-    - |
-      if [[ ${PRE_EXIT_CODE} -ne 0 ]]; then
-        exit ${PRE_EXIT_CODE}
-      fi
-      if [[ ${EXIT_CODE} -ne 0 ]]; then
-        exit ${EXIT_CODE}
-      fi
   artifacts:
     paths:
       - "test-artifacts/"
@@ -329,10 +326,6 @@ aws/rke2/bigbang test:
     - ./scripts/hosts.sh
     - echo -e "\e[0Ksection_end:`date +%s`:host_setup\r\e[0K"
     - *test_bigbang
-    - |
-      if [[ ${EXIT_CODE} -ne 0 ]]; then
-        exit ${EXIT_CODE}
-      fi
   environment:
     name: review/aws-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
   allow_failure:
