see if that works

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -93,7 +93,11 @@ pre vars:
     for test_script in $(find ./tests/tests -type f -name '*.sh' | sort); do
       chmod +x ${test_script}
       echo "Executing ${test_script}..."
-      ./${test_script}
+      ./${test_script} && export EXIT_CODE=$? || export EXIT_CODE=$?
+      if [[ ${EXIT_CODE} -ne 0 ]]; then
+        echo "${test_script} failed, see log output above and cluster debug."
+        exit ${EXIT_CODE}
+      fi
     done
 
 clean install:
