fix font, added 123 exit for upgrade

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -114,7 +114,7 @@ pre vars:
       echo -e "\e[0Ksection_end:`date +%s`:${test_script##*/}\r\e[0K"
     done
     if [[ ${EXIT_FLAG} -ne 0 ]]; then
-      echo -e "\[31mWARNING: One or more BB tests failed but were allowed to continue. See output of scripts above for details.\e[0m"
+      echo -e "\e[31mWARNING: One or more BB tests failed but were allowed to continue. See output of scripts above for details.\e[0m"
     fi
 
 clean install:
@@ -171,7 +171,6 @@ upgrade:
     - echo -e "\e[0Ksection_end:`date +%s`:git_master\r\e[0K"
     - *deploy_bigbang
     - *test_bigbang
-    - PRE_EXIT_CODE=${EXIT_FLAG}
     - echo "Upgrade Big Bang from ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
     - echo -e "\e[0Ksection_start:`date +%s`:git_upgrade[collapsed=true]\r\e[0K\e[33;1mGit Upgrade\e[37m"    
     - git reset --hard && git clean -fd
@@ -179,6 +178,11 @@ upgrade:
     - echo -e "\e[0Ksection_end:`date +%s`:git_upgrade\r\e[0K"
     - *deploy_bigbang
     - *test_bigbang
+    - |
+      if [[ ${EXIT_FLAG} -eq 1 ]]; then
+        # failures occurred but were allowed to continue
+        exit 123
+      fi
   artifacts:
     paths:
       - "test-artifacts/"
