loops on everything

diff --git a/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml b/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml
--- a/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml
+++ b/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml
@@ -37,4 +37,17 @@
   script:
     - *calc_unique_cidr
     - echo "Destroying network"
-    - terraform destroy -auto-approve
+    # Loop to retry network terraform destory
+    - |
+      set -e
+      attempt_counter=0
+      max_attempts=2
+      until [ $(terraform destroy -auto-approve >/dev/null; echo $?) -eq 0 ]; do
+        if [ ${attempt_counter} == ${max_attempts} ];then
+          echo "Error destroying network terraform"
+          exit 1
+        fi
+        attempt_counter=$(($attempt_counter+1))
+        echo "First attempt failed to destroy will retry in 30 seconds"
+        sleep 30
+      done
diff --git a/.gitlab-ci/jobs/rke2/.gitlab-ci.yml b/.gitlab-ci/jobs/rke2/.gitlab-ci.yml
--- a/.gitlab-ci/jobs/rke2/.gitlab-ci.yml
+++ b/.gitlab-ci/jobs/rke2/.gitlab-ci.yml
@@ -32,4 +32,17 @@
     - .rke2 tf
     - .terraform destroy workspace
   script:
-    - terraform destroy -input=false -auto-approve
+    # Loop to retry rke2 terraform destory
+    - |
+      set -e
+      attempt_counter=0
+      max_attempts=2
+      until [ $(terraform destroy -input=false -auto-approve >/dev/null; echo $?) -eq 0 ]; do
+        if [ ${attempt_counter} == ${max_attempts} ];then
+          echo "Error destroying rke2 cluster terraform"
+          exit 1
+        fi
+        attempt_counter=$(($attempt_counter+1))
+        echo "First attempt failed to destroy will retry in 30 seconds"
+        sleep 30
+      done
diff --git a/.gitlab-ci/templates.yml b/.gitlab-ci/templates.yml
--- a/.gitlab-ci/templates.yml
+++ b/.gitlab-ci/templates.yml
@@ -41,4 +41,17 @@ include:
 .terraform destroy workspace:
   after_script:
     - cd ${CI_PROJECT_DIR}/${TF_ROOT}
-    - terraform workspace select default && terraform workspace delete "${TF_VAR_env}"
+    # Loop to retry terraform workspace destory
+    - |
+      set -e
+      attempt_counter=0
+      max_attempts=2
+      until [ $(terraform workspace select default >/dev/null && terraform workspace delete "${TF_VAR_env}" >/dev/null; echo $?) -eq 0 ]; do
+        if [ ${attempt_counter} == ${max_attempts} ];then
+          echo "Error destroying terraform workspace"
+          exit 1
+        fi
+        attempt_counter=$(($attempt_counter+1))
+        echo "First attempt failed to destroy workspace will retry in 30 seconds"
+        sleep 30
+      done
