set -e and comments

diff --git a/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml b/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml
--- a/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml
+++ b/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml
@@ -15,11 +15,12 @@
   script:
     - *calc_unique_cidr
     - echo "Creating network with cidr range ${TF_VAR_vpc_cidr}"
-    # Loop to retry terraform apply due to issues locking terraform.state in s3
+    # Loop to retry network up terraform apply due to issues locking terraform.state in s3
     - |
+      set -e
       attempt_counter=0
       max_attempts=2
-      until [[ $(terraform apply -auto-approve >/dev/null; echo $?) -eq 0 ]]; do
+      until [ $(terraform apply -auto-approve >/dev/null; echo $?) -eq 0 ]; do
         if [ ${attempt_counter} == ${max_attempts} ];then
           echo "Error applying network up terraform"
           exit 1
@@ -28,7 +29,6 @@
         echo "First attempt failed to apply will retry in 30 seconds"
         sleep 30
       done
-    #- terraform apply -auto-approve
 
 .network down:
   extends:
diff --git a/.gitlab-ci/jobs/rke2/.gitlab-ci.yml b/.gitlab-ci/jobs/rke2/.gitlab-ci.yml
--- a/.gitlab-ci/jobs/rke2/.gitlab-ci.yml
+++ b/.gitlab-ci/jobs/rke2/.gitlab-ci.yml
@@ -8,7 +8,20 @@
   script:
     # Fetch dependencies
     - apk add bash aws-cli
-    - terraform apply -input=false -auto-approve
+    # Loop to retry rke2 terraform apply
+    - |
+      set -e
+      attempt_counter=0
+      max_attempts=2
+      until [ $(terraform apply -input=false -auto-approve >/dev/null; echo $?) -eq 0 ]; do
+        if [ ${attempt_counter} == ${max_attempts} ];then
+          echo "Error applying rke2 cluster up terraform"
+          exit 1
+        fi
+        attempt_counter=$(($attempt_counter+1))
+        echo "First attempt failed to apply will retry in 30 seconds"
+        sleep 30
+      done
     - mv rke2.yaml ${CI_PROJECT_DIR}/rke2.yaml
   artifacts:
     paths:
